set SERVEROUTPUT ON ;
SET SERVEROUTPUT ON; 

Create Table testa 
(
	MANV VARCHAR2(20) Primary key,
	MACHUCVU VARCHAR2(20) not null
	
)

Create Table NHANVIEN 
(
	MANV VARCHAR2(20) Primary key,
	MACHUCVU VARCHAR2(20) not null,
	MABOPHAN VARCHAR2(20)not null,
	HONV VARCHAR2(150) not null,
	TENNV VARCHAR2 (50) not null, 
	GIOITINH VARCHAR2(20) not null,
	NGAYSINH DATE not null, 
	DIACHI VARCHAR2(250) not null,
	DIENTHOAI VARCHAR2(20) not null,
	EMAIL VARCHAR2(50) not null
)

alter table NHANVIEN add constraint FK_NHANVIEN_BOPHAN foreign key (MaBoPhan) references BOPHAN (MaBoPhan)
alter table NHANVIEN add constraint FK_NHANVIEN_CHUCVU foreign key (MaChucVu) references CHUCVU (MaChucVu)

Create Table KHACHHANG
(
	MaKh VARCHAR2(20) primary key,
	MaLoaiKhachHang VARCHAR2(20) not null,
	HoKh VARCHAR2(100) not null,
	TenKh VARCHAR2(30) not null,
	GioiTinh VARCHAR2(20) not null,
	DiaChi VARCHAR2(150) not null,
	DienThoai VARCHAR2(30) not null,
	Email VARCHAR2(50) not null,
	CMND VARCHAR2(30) not null
)

alter table KHACHHANG add constraint FK_KHACHHANG_LKH foreign key (MaLoaiKhachHang) references LOAIKHACHHANG (MaLoaiKhachHang)

Create Table CHUCVU
(
	MaChucVu VARCHAR2(20) primary key,
	TenChucVu VARCHAR2(50) not null
)

Create Table BOPHAN
(
	MaBoPhan VARCHAR2(20) primary key,
	TenBoPhan VARCHAR2(50) not null,
	NgayThanhLap DATE not null
)

Create Table LOAIKHACHHANG
(
	MaLoaiKhachHang VARCHAR2(20) primary key,
	TenLoaiKhachHang VARCHAR2(50) not null
)

Create Table DICHVU
(
	MaDichVu VARCHAR2(20) primary key,
	MaLoaiDichVu VARCHAR2(10) not null,
	TenDichVu VARCHAR2(100) not null
)

alter table DICHVU add constraint FK_DICHVU_LDV foreign key (MaLoaiDichVu) references LOAIDICHVU (MaLoaiDichVu)
---------------------------------------------------------------------------------------------------------------------------------------------------------
Create Table LOAIDICHVU
(
	MaLoaiDichVu VARCHAR2(20) primary key,
	DonGiaDichVu FLOAT not null,
	NgaySuDungDichVu DATE not null
)

Create Table TINHTRANGPHONG
(
	MaTinhTrangPhong VARCHAR2(20) primary key,
	TenTinhTrangPhong VARCHAR2(100) not null
)

Create Table PHONG
(
	MaPhong VARCHAR2(20) primary key, 
	MaLoaiPhong VARCHAR2(20) not null,
	MaTinhTrangPhong VARCHAR2(10) not null,
	SoGiuong VARCHAR2(20) not null,
    GIAPHONG FLOAT not null,
    DONVITINH VARCHAR2(20) not null
)

alter table PHONG add constraint FK_PHONG_LP foreign key (MaLoaiPhong) references LOAIPHONG (MaLoaiPhong)
alter table PHONG add constraint FK_PHONG_TTP foreign key (MaTinhTrangPhong) references TINHTRANGPHONG (MaTinhTrangPhong)

Create Table LOAIPHONG
(
	MaLoaiPhong VARCHAR2(20) primary key,
	TenLoaiPhong VARCHAR2(100) not null
)

Create table PHIEUTHUEPHONG
(
    MaPhieuThuePhong VARCHAR2(20) primary key,
    MaKH VARCHAR2(20) not null,
    MaPhong VARCHAR2(20) not null,
    NgayThuePhong DATE not null,
    NgayTraPhong DATE not null
)

alter table PHIEUTHUEPHONG add constraint FK_PHIEUTHUEPHONG_PHONG FOREIGN KEY (MaPhong) references PHONG (MaPhong)

alter table PHIEUTHUEPHONG add constraint FK_PHIEUTHUEPHONG_KHACHHANG foreign key (MAKH) REFERENCES KHACHHANG (MaKH)


Create table CTPHIEUTHUEPHONG
(
    MaCTPhieuThuePhong VARCHAR2(20) primary key,
    MaPhieuThuePhong VARCHAR2(20) not null,
    SoTienDatCoc FLOAT not null
)

alter table CTPHIEUTHUEPHONG add constraint FK_PHIEUTHUEPHONG_CTPTP foreign key (MaPhieuThuePhong) references PHIEUTHUEPHONG (MaPhieuThuePhong)
CREATE TABLE HOADON
(
    MaHoaDon VARCHAR2(20) primary key,
    MaLoaiDichVu VARCHAR2(20) not null,
    MaNV VARCHAR2(20) not null,
    MaCTPhieuThuePhong VARCHAR2(20) not null, 
    NgayLapHoaDon DATE not null
)

alter table HOADON add constraint FK_HOADON_LDV foreign key (MaLoaiDichVu) references LOAIDICHVU (MaLoaiDichVu)
alter table HOADON add constraint  FK_HOADON_NV foreign key (MaNV) references NHANVIEN (MaNV) 
alter table HOADON add constraint FK_HOADON_CTPT foreign key (MaCTPhieuThuePhong) references CTPHIEUTHUEPHONG (MaCTPhieuThuePhong)


CREATE TABLE VATTU
(
    MAVATTU VARCHAR2(20) primary key,
    TENVATTU VARCHAR2(20) not null
)

CREATE TABLE CTVATTU
(
    MAVATTU VARCHAR2(20) not null,
    MAPHONG VARCHAR2(20) not null,
    SOLUONGVATTU VARCHAR2(200) not null,
    primary key (MAVATTU,MAPHONG)
)


alter table CTVATTU add constraint FK_CTVATTU foreign key (MAVATTU) references VATTU (MAVATTU)
----------------------------- L?I
alter table CTVATTU add constraint FK_PHONG_CTVATTU foreign key (MAPHONG) references PHONG (MAPHONG)




-------------------DU LIEU NHANVIEN---------------------------------
INSERT INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH,
DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0001','CV04','BP02','Nguyen Thi Bich Phuong','Phuong','Nu',
TO_DATE('2002/10/12','yyyy/mm/dd'),'Dong Nai','0933329203','nguyenthibichphuong@gmail.com');
INSERT INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, 
DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0002','CV03','BP01','Tran','Dan','Nam',
TO_DATE('2001/06/22','yyyy/mm/dd'),'Ngo 6,pho Thanh Xuan, Ha Noi','098123123','trandan1223@gmail.com');
INSERT INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, 
DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0003','CV02','BP01', N'Nguyen Van Tuan', N'Minh', N'Nam',
TO_DATE('2002/10/13','yyyy/mm/dd'),'80 Tan Huong,Quan Tan Phu,TPHCM','0123456789','nguyevantuanminh@gmail.com');
INSERT INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH,
DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0004','CV01','BP01', N'Dinh Ngoc Quynh', N'Trang', N'Nu',
TO_DATE('2000/11/23','yyyy/mm/dd'),'263/2 Binh Thanh,Quan Binh Tan, TPHCM','0124114142','dinhngocquynhmo@gmail.com');
INSERT INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0005','CV04','BP01', N'Le Nhat Dang', N'Khoa', N'Nam',
TO_DATE('2000/12/02','yyyy/mm/dd'),'21 Go Diu TP Binh Thuan','0823746191','dangkhoane@gmail.com');
INSERT   INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0006','CV04','BP02', N'Nguyen Trinh Thu', N'Ngan', N'Nu',TO_DATE('2000/08/02','yyyy/mm/dd'),'60/40 Nguyen San Quan,Tan Phu TPHCM','0963341637','nguyentrinhthungan@gmail.com');
INSERT   INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0007','CV01','BP03', N'Tran', N'Hoong', N'Nam',TO_DATE('1989/08/02','yyyy/mm/dd'),'299/9/12 Binh Thanh Quan Binh Tan TPHCM','03453415665','tranhoang@gmail.com');
INSERT   INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0012','CV04','BP03', N'Le Trong', N'Lan', N'Nam',TO_DATE('1999/08/02','yyyy/mm/dd'),'3 Le Lai TP HCM','0923847021','Letrongluan@gmail.com');
INSERT   INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0013','CV01','BP04', N'Le Nhat', N'Phi', N'Nam',TO_DATE('2000/12/02','yyyy/mm/dd'),'23/34/2 Tay Thanh TP HCM','0712384957', N'lenhatphi@gmail.com');
INSERT   INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0014','CV02','BP04', N'Nguyen Tran', N'Phi',N'Nam',TO_DATE('2002/11/02','yyyy/mm/dd'),'23/2 Le Trong Tan','09218763872',N'nguyentranphi@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0015','CV03','BP04', N'Nguyen Thi Thuy', N'Tien', N'Nu',TO_DATE('2003/09/02','yyyy/mm/dd'),'83/12 Le Lu TP HCM','092135873',N'nguyenthithuytien@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0018','CV02','BP05',N'Nguyen Ä?inh',N'Thong',N'Nam',TO_DATE('1979/08/04','yyyy/mm/dd'),'34 Nguyen Thai Hoc TP HCM','0928765289',N'nguyendinhthong@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0016','CV04','BP04', N'Nguyen Minh', N'Tri', N'Nam', TO_DATE('1988/02/14','yyyy/mm/dd'),'3/1 Le Cao Lang TP HCM','0712345674', 'nguyeminhtri@gmai.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0019','CV03','BP05',N'Ho Nguyen',N'Nhu',N'Nu',TO_DATE('1998/08/09','yyyy/mm/dd'),'45 Le Thuc Hoach','09128374812','honguyennhu@gmail.com');
INSERT INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0020','CV01','BP06', N'Tran Ngoc Bao',N'Han',N'Nu',TO_DATE('1993/08/13','yyyy/mm/dd'), '32 Le Van Viet TP HCM','0918274263','tranngocbaohan@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0021','CV02','BP06', N'Vo Dinh Gia', N'Huan', N'Nam',TO_DATE('2000/08/22','yyyy/mm/dd'),'32 D2 TP HCM','0918273648','vodinhgiahuan');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0022','CV03','BP06',N'Nguyen Tue',N'An',N'Nu',TO_DATE('2002/04/12','yyyy/mm/dd'),'2 385 TP HCM','0982716282','nguyentuean@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0023','CV04','BP06',N'Vo Hong Khanh',N'Vy',N'Nu',TO_DATE('2001/02/02','yyyy/mm/dd'),'21 Tan Ky Tan Quy','0918273921','vohongkhachvy@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0024','CV01','BP07', N'Nguyen Phu', N'Loi', N'Nam',TO_DATE('2001/07/02','yyyy/mm/dd'),'455 Pham The Hien TP C0912348503 HCM','09182137431','nguyenphuloi@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0025','CV02','BP07', N'Tran Minh', N'Nhut', N'Nam',TO_DATE('2000/04/30','yyyy/mm/dd'),'2 Tan Quy TP HCM','09182723612','tranminhnnhut@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0026','CV03','BP07', N'Tran Thuy Thanh', N'Tam',N'Nu',TO_DATE('2000/08/02','yyyy/mm/dd'),'21 Duong Van Duong TP HCM','0921345325','tranthuythanhtam@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0027','CV04','BP07',N'Vo Thi Bao', N'Uyen', N'Nu',TO_DATE('2001/04/25','yyyy/mm/dd'),'32 Duong so 3 TP HCM','091235423621','vothibaouyen@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0028','CV01','BP08',N'Tran',N'Duc',N'Nam',TO_DATE('2000/08/18','yyyy/mm/dd'),'299/9/12 Binh Thanh TP HCM','0764464486','trandc3015@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0029','CV02','BP08',N'Dang Thanh',N'Lam',N'Nu',TO_DATE('1999/08/02','yyyy/mm/dd'),'12 duong so 4 TP HCM','0911234567','dangthanhlam@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0030','CV03','BP08',N'Le',N'Trang',N'Nu',TO_DATE('1986/08/28','yyyy/mm/dd'),'34 ap Chien Luoc TP HCM','0712387421','letrangne@gmail.com'); 
INSERT INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0031','CV01','BP06', N'Tran Th?',N'Han',N'Nu',TO_DATE('1993/08/13','yyyy/mm/dd'), '32 Le Van Viet TP HCM','0918274263','tranngocbaohan@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0032','CV02','BP06', N'Vo Dinh Duong', N'Minh', N'Nam',TO_DATE('2000/08/22','yyyy/mm/dd'),'32 D2 TP HCM','0918273648','vodinhduongminh');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0033','CV03','BP06',N'Nguyen Khánh',N'An',N'Nu',TO_DATE('2002/04/12','yyyy/mm/dd'),'2 385 TP HCM','0982716282','nguyenkhanhan@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0034','CV04','BP06',N'Vo Thi Khanh',N'Vy',N'Nu',TO_DATE('2001/02/02','yyyy/mm/dd'),'21 Tan Ky Tan Quy','0918273921','vothikhachvy@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0035','CV01','BP07', N'Nguyen Phu Quy', N'Loi', N'Nam',TO_DATE('2001/07/02','yyyy/mm/dd'),'455 Pham The Hien TP C0912348503 HCM','09182137431','nguyenphuqiuloi@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0036','CV02','BP07', N'Tran Minh Dang', N'Nhut', N'Nam',TO_DATE('2000/04/30','yyyy/mm/dd'),'2 Tan Quy TP HCM','09182723612','tranminhdangnnhut@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0037','CV03','BP07', N'Tran Ngoc Thanh', N'Thuy',N'Nu',TO_DATE('2000/08/02','yyyy/mm/dd'),'21 Duong Van Duong TP HCM','0921345325','tranngocthanhthuy@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0038','CV04','BP07',N'Vo Thi Buu', N'Ngoc', N'Nu',TO_DATE('2001/04/25','yyyy/mm/dd'),'32 Duong so 3 TP HCM','091235423621','vothibuungoc@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0039','CV01','BP08',N'Tran',N'Hoang',N'Nam',TO_DATE('2000/08/18','yyyy/mm/dd'),'299/9/12 Binh Thanh TP HCM','0764464486','tranhoang3015@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0040','CV02','BP08',N'Nguyen Thanh Tam',N'Lam',N'Nu',TO_DATE('1999/08/02','yyyy/mm/dd'),'12 duong so 4 TP HCM','0911234567','nguyenthanhlam@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0041','CV03','BP08',N'Le',N'Lan',N'Nu',TO_DATE('1986/08/28','yyyy/mm/dd'),'34 ap Chien Luoc TP HCM','0712387421','lelanne@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0042','CV03','BP06',N'Nguyen Khanh',N'An',N'Nu',TO_DATE('2002/04/12','yyyy/mm/dd'),'2 385 TP HCM','0982716282','nguyenkhanhan@gmail.com');

INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0043','CV04','BP06',N'Cao',N'Lam',N'Nam',
TO_DATE('2001/02/02','yyyy/mm/dd'),'21 Tan Ky Tan Quy','0918273921','caoLam@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0044','CV01','BP07', N'Nguyen Phu', N'Quy', N'Nam',
TO_DATE('2001/07/02','yyyy/mm/dd'),'455 Pham The Hien TP C0912348503 HCM','09182137431','nguyenphuloi@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0045','CV02','BP07', N'Tran Minh', N'Dang', N'Nam',
TO_DATE('2000/04/30','yyyy/mm/dd'),'2 Tan Quy TP HCM','09182723612','tranminhdang@gmail.com');

INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0046','CV03','BP07', N'Bui Thi Doan', N'Trang',N'Nu',
TO_DATE('2000/08/02','yyyy/mm/dd'),'21 Duong Van Duong TP HCM','0921345325','buithidoantrang@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0047','CV04','BP07',N'Ha Tan', N'Minh', N'Nam',
TO_DATE('2001/04/25','yyyy/mm/dd'),'32 Duong so 3 TP HCM','091235423621','hatanminh@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0048','CV01','BP08',N'Tran Minh',N'Beo',N'Nam',
TO_DATE('2000/08/18','yyyy/mm/dd'),'299/9/12 Binh Thanh TP HCM','0764464486','tranminhbeo@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0049','CV02','BP08',N'Nguyen Thi Bich',N'Phuong',N'Nu',
TO_DATE('1999/08/02','yyyy/mm/dd'),'12 duong so 4 TP HCM','0911234567','ntbp@gmail.com');
INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) 
VALUES ('NV0050','CV03','BP08',N'Le',N'Mo',N'Nu',
TO_DATE('1986/08/28','yyyy/mm/dd'),'34 ap Chien Luoc TP HCM','0712387421','lemo@gmail.com');
 

 
   
            
     
 ------------------DU LIEU KHACHHANG------------------------- 
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH,
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH001','LKH02','Tran','Duc','Nam','Quan Tan Phu, TPHCM',
'0855 526 437',N'trduc123@gmail.com','02116584441');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, 
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH002','LKH02',N'Ho Thanh',N'Phuoc',N'Nam',N'Quan Tan Binh, TPHCM',
'09825151854',N'hothanhphuoc@gmail.com','02116584441');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH,
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH003','LKH01',N'Le Ä?uc',N'Minh',N'Nam',N'31 Nguyen Xi',
'098214145',N'leducminh@gmail.com','02116584448');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH,
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH004','LKH02',N'Vo Cam ',N'Nhung',N'Nu',N'71 Quang Trung',
'09825451854',N'vocamnhung@gmail.com','02116584442');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH,
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH005','LKH01',N'Hoang Khanh ',N'Hung',N'Nam',N'93 Quoc lo 13',
'09845151854',N'hoangkhanhhung@gmail.com','02116584448');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH,
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH006','LKH02',N'Do Ngoc ',N'Linh',N'Nu',N'71 Huynh Thuc Khang',
'09825141854',N'dongoclinh@gmail.com','0812665018');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH007','LKH02',N'Le Van ',N'Khuong',N'Nam',N'455 Xo Viet Nghe Tinh','09225151854',N'levankhuong@gmail.com','02116584444');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH008','LKH01',N'Mai Hoang ',N'Ä?uc',N'Nam',N'93 Quoc lo 13','0985151854',N'maihoangduc@gmail.com','02116584443');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH009','LKH02',N'Tran Ngoc',N'Ä?an',N'Nu',N'71 Quang Trung','09825151854',N'tranngocdan@gmail.com','02116584446');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH010','LKH01',N'Tran ',N'An',N'Nam',N'72 Quang Trung','09825151814',N'tranan@gmail.com','07927382672');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH011','LKH02',N'Tran Ngoc',N'Chau',N'Nam','2 Tan Quy TP HCM','0978271823',N'tranngocanhmai@gmail.com','09273648272');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH012','LKH01',N'Tran',N'Dan',N'Nam','72 Quang Trung','09825151814',N'tranngocan@gmail.com','09116584446');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH013','LKH02',N'Nguyen Minh',N'Ä?ang',N'Nam',N'79 Binh Thuan','0921823648',N'nguyenminhdang@gmail.com','0978398172');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH014','LKH01',N'Nguyen Hoang Thanh',N'An',N'Nu','32/23 Quang Trung TP HCM','0298724694',N'nguyenhoangthanhan@gmail.com','0876386213');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH015','LKH02',N'Bui Manh',N'Hung',N'Nam',N'215/37 Huynh Van Banh TP HCM','0987263743',N'buimanhhung@gmail.com','07214892371');


INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH016','LKH02','Tran','Duc','Nam','Quan Tan Phu, TPHCM','0855 526 437',N'trduc123@gmail.com','02116584441');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH017','LKH02',N'Ho Thanh',N'Phuoc',N'Nam',N'Quan Tan Binh, TPHCM','09825151854',N'hothanhphuoc@gmail.com','02116584441');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH018','LKH01',N'Le Ä?uc',N'Minh',N'Nam',N'31 Nguyen Xi','098214145',N'leducminh@gmail.com','02116584448');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH019','LKH02',N'Vo Cam ',N'Nhung',N'Nu',N'71 Quang Trung','09825451854',N'vocamnhung@gmail.com','02116584442');


INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH020','LKH02','Tran','Te','Nam','Quan Tan Phu, TPHCM','0855 526 437',N'trduc123@gmail.com','02116584441');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH021','LKH02',N'Ho Khang',N'Phuoc',N'Nam',N'Quan Tan Binh, TPHCM','09825151854',N'hothanhphuoc@gmail.com','02116584441');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH022','LKH01',N'Le Ja',N'Minh',N'Nam',N'31 Nguyen Xi','098214145',N'leducminh@gmail.com','02116584448');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH023,'LKH02',N'Vo Cam Vi',N'Nhung',N'Nu',N'71 Quang Trung','09825451854',N'vocamnhung@gmail.com','02116584442');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH024','LKH01',N'Hoang Linh',N'Hung',N'Nam',N'93 Quoc lo 13','09845151854',N'hoangkhanhhung@gmail.com','02116584448');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH025','LKH02',N'Do Phuoc',N'Linh',N'Nu',N'71 Huynh Thuc Khang','09825141854',N'dongoclinh@gmail.com','0812665018');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH026','LKH02',N'Le Thi',N'Khuong',N'Nam',N'455 Xo Viet Nghe Tinh','09225151854',N'levankhuong@gmail.com','02116584444');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH027','LKH01',N'Mai Lâm',N'Duc',N'Nam',N'93 Quoc lo 13','0985151854',N'maihoangduc@gmail.com','02116584443');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH028','LKH02',N'Tran Quynh',N'Tra',N'Nu',N'71 Quang Trung','09825151854',N'tranngocdan@gmail.com','02116584446');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH029','LKH01',N'Tran ',N'Quý',N'Nam',N'72 Quang Trung','09825151814',N'tranan@gmail.com','07927382672');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH030','LKH02',N'Tran Ngoc',N'Tra',N'Nam','2 Tan Quy TP HCM','0978271823',N'tranngocanhmai@gmail.com','09273648272');

INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH031','LKH01',N'Hoang Khanh ',N'Hung',N'Nam',N'93 Quoc lo 13','09845151854',N'hoangkhanhhung@gmail.com','02116584448');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH032','LKH02',N'Do Ngoc ',N'Linh',N'Nu',N'71 Huynh Thuc Khang','09825141854',N'dongoclinh@gmail.com','0812665018');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH033','LKH02',N'Le Van ',N'Khuong',N'Nam',N'455 Xo Viet Nghe Tinh','09225151854',N'levankhuong@gmail.com','02116584444');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH034','LKH01',N'Mai Hoang ',N'Ä?uc',N'Nam',N'93 Quoc lo 13','0985151854',N'maihoangduc@gmail.com','02116584443');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH035','LKH02',N'Tran Ngoc',N'Ä?an',N'Nu',N'71 Quang Trung','09825151854',N'tranngocdan@gmail.com','02116584446');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH036','LKH01',N'Tran ',N'An',N'Nam',N'72 Quang Trung','09825151814',N'tranan@gmail.com','07927382672');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH037','LKH02',N'Tran Ngoc',N'Chau',N'Nam','2 Tan Quy TP HCM','0978271823',N'tranngocanhmai@gmail.com','09273648272');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH038','LKH01',N'Tran',N'Dan',N'Nam','72 Quang Trung','09825151814',N'tranngocan@gmail.com','09116584446');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH039','LKH02',N'Nguyen Minh',N'Ä?ang',N'Nam',N'79 Binh Thuan','0921823648',N'nguyenminhdang@gmail.com','0978398172');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH040','LKH01',N'Nguyen Hoang Thanh',N'An',N'Nu','32/23 Quang Trung TP HCM','0298724694',N'nguyenhoangthanhan@gmail.com','0876386213');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH041','LKH02',N'Bui Manh',N'Hung',N'Nam',N'215/37 Huynh Van Banh TP HCM','0987263743',N'buimanhhung@gmail.com','07214892371');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH042','LKH02',N'Do Ngoc ',N'Linh',N'Nu',N'71 Huynh Thuc Khang','09825141854',N'dongoclinh@gmail.com','0812665018');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) VALUES ('KH043','LKH02',N'Le Van ',N'Khuong',N'Nam',N'455 Xo Viet Nghe Tinh','09225151854',N'levankhuong@gmail.com','02116584444');

INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH,
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH044','LKH01',N'Mai Hoang ',N'Ä?uc',N'Nam',N'93 Quoc lo 13',
'0985151854',N'maihoangduc@gmail.com','02116584443');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH,
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH045','LKH02',N'Tran Ngoc',N'Ä?an',N'Nu',N'71 Quang Trung',
'09825151854',N'tranngocdan@gmail.com','02116584446');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH,
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH046','LKH01',N'Tran ',N'An',N'Nam',N'72 Quang Trung',
'09825151814',N'tranan@gmail.com','07927382672');

INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH,
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH047','LKH02',N'Tran Ngoc',N'Chau',N'Nam','2 Tan Quy TP HCM',
'0978271823',N'tranngocanhmai@gmail.com','09273648272');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, 
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH048','LKH01',N'Tran',N'Dan',N'Nam','72 Quang Trung',
'09825151814',N'tranngocan@gmail.com','09116584446');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, 
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH049','LKH02',N'Nguyen Minh',N'Ä?ang',N'Nam',N'79 Binh Thuan',
'0921823648',N'nguyenminhdang@gmail.com','0978398172');
INSERT INTO KHACHHANG (MAKH, MALOAIKHACHHANG, HOKH,TENKH, 
GIOITINH, DIACHI, DIENTHOAI, EMAIL, CMND) 
VALUES ('KH050','LKH01',N'Nguyen Hoang Thanh',N'An',N'Nu','32/23 Quang Trung TP HCM',
'0298724694',N'nguyenhoangthanhan@gmail.com','0876386213');

  SELECT count (*) FROM KHACHHANG;   
   


 ---------------DU LIEU LOAIKHACHHANG----------------
INSERT INTO LOAIKHACHHANG (MaLoaiKhachHang, TenLoaiKhachHang) VALUES ('LKH01','Khach hang moi');
INSERT INTO LOAIKHACHHANG (MaLoaiKhachHang, TenLoaiKhachHang) VALUES('LKH02','Khach hang VIP');

 ---------------DU LIEU CHUCVU----------------
INSERT INTO CHUCVU (MaChucVu,TenChucVu) VALUES ('CV01', N'Giam doc');
INSERT INTO CHUCVU (MaChucVu,TenChucVu) VALUES('CV02', N'Pho giam doc');
INSERT INTO CHUCVU (MaChucVu,TenChucVu) VALUES('CV03', N'Truong phong');
INSERT INTO CHUCVU (MaChucVu,TenChucVu) VALUES('CV04', N'Nhan vien');


 ---------------DU LIEU BOPHAN----------------
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP01', N'Bo phan dieu hanh',TO_DATE('1992/03/17','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP02', N'Bo phan le tan', TO_DATE('1992/03/20','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP03', N'Bo phan buong phong',TO_DATE('1992/03/23','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP04', N'Bo phan am thuc',TO_DATE('1992/05/03','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP05', N'Bo phan bep',TO_DATE('1992/05/17','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP06', N'Bo phan kinh doanh tiep thi',TO_DATE('1992/05/18','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP07', N'Bo phan tai chinh - ke toan', TO_DATE('1992/05/16','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP08', N'Bo phan hanh chinh - nhan su',TO_DATE('1992/05/22','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP09', N'Bo phan ky thuat bao tri',TO_DATE('1992/06/02','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP10', N'Bo phan cong nghe thong tin',TO_DATE('1992/09/02','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP11', N'Bo phan an ninh',TO_DATE('1992/11/02','yyyy/mm/dd'));
INSERT INTO BOPHAN (MaBoPhan,TenBoPhan, NgayThanhLap) VALUES 
('BP12',N'Bo phan the thao va giai tri',TO_DATE('1993/01/02','yyyy/mm/dd'));




 ------------------DU LIEU HOADON------------------------- 
INSERT INTO HOADON VALUES('HD0001','GUI','NV0001','CTPTP001',TO_DATE('2016-02-01','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0002','KAO','NV0002','CTPTP002',TO_DATE('2016-02-02','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0003','DUA','NV0003','CTPTP003',TO_DATE('2016-02-12','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0004','GUI','NV0004','CTPTP004',TO_DATE('2016-02-13','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0005','KAO','NV0005','CTPTP005',TO_DATE('2016-02-14','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0006','DUA','NV0006','CTPTP006',TO_DATE('2016-02-15','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0007','GUI','NV0007','CTPTP007',TO_DATE('2016-02-07','yyyy/mm/dd'));

INSERT INTO HOADON VALUES('HD0012','GUI','NV0012','CTPTP012',TO_DATE('2016-02-12','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0013','KAO','NV0013','CTPTP013',TO_DATE('2019-09-13','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0014','DUA','NV0014','CTPTP014',TO_DATE('2019-09-14','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0016','KAO','NV0016','CTPTP016',TO_DATE('2019-09-16','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0018','GUI','NV0018','CTPTP018',TO_DATE('2019-09-18','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0019','KAO','NV0019','CTPTP019',TO_DATE('2019-09-19','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0020','DUA','NV0020','CTPTP020',TO_DATE('2019-09-20','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0021','GUI','NV0021','CTPTP021',TO_DATE('2020-11-21','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0022','KAO','NV0022','CTPTP022',TO_DATE('2020-11-22','yyyy/mm/dd'));

INSERT INTO HOADON VALUES('HD0024','GUI','NV0024','CTPTP024',TO_DATE('2020-11-24','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0025','KAO','NV0025','CTPTP025',TO_DATE('2021-01-25','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0026','DUA','NV0026','CTPTP026',TO_DATE('2021-01-26','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0027','KAO','NV0027','CTPTP027',TO_DATE('2021-01-27','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0028','DUA','NV0028','CTPTP028',TO_DATE('2021-01-28','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0029','KAO','NV0029','CTPTP029',TO_DATE('2021-01-29','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0030','DUA','NV0030','CTPTP030',TO_DATE('2021-01-30','yyyy/mm/dd'));



INSERT INTO HOADON VALUES('HD0031','GUI','NV0001','CTPTP001',TO_DATE('2023-02-01','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0032','KAO','NV0002','CTPTP002',TO_DATE('2016-02-02','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0033','DUA','NV0003','CTPTP003',TO_DATE('2016-02-12','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0034','GUI','NV0004','CTPTP004',TO_DATE('2016-02-13','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0035','KAO','NV0005','CTPTP005',TO_DATE('2016-02-14','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0036','DUA','NV0006','CTPTP006',TO_DATE('2016-02-15','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0037','GUI','NV0007','CTPTP007',TO_DATE('2016-02-07','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0038','GUI','NV0012','CTPTP012',TO_DATE('2016-02-12','yyyy/mm/dd'));

INSERT INTO HOADON VALUES('HD0039','KAO','NV0013','CTPTP013',TO_DATE('2019-09-13','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0040','DUA','NV0014','CTPTP014',TO_DATE('2019-09-14','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0041','KAO','NV0016','CTPTP016',TO_DATE('2019-09-16','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0042','GUI','NV0018','CTPTP018',TO_DATE('2019-09-18','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0043','KAO','NV0019','CTPTP019',TO_DATE('2019-09-19','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0044','DUA','NV0020','CTPTP020',TO_DATE('2019-09-20','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0045','KAO','NV0016','CTPTP016',TO_DATE('2019-09-16','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0046','GUI','NV0018','CTPTP018',TO_DATE('2019-09-18','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0047','KAO','NV0019','CTPTP019',TO_DATE('2019-09-19','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0048','DUA','NV0020','CTPTP020',TO_DATE('2019-09-20','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0049','KAO','NV0019','CTPTP019',TO_DATE('2019-09-19','yyyy/mm/dd'));
INSERT INTO HOADON VALUES('HD0050','DUA','NV0020','CTPTP020',TO_DATE('2019-09-20','yyyy/mm/dd'));

 ------------------DU LIEU CTPHIEUTHUEPHONG------------------------- 
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP001','PTP001','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP002','PTP002','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP003','PTP003','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP004','PTP004','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP005','PTP005','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP006','PTP006','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP007','PTP007','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP008','PTP008','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP009','PTP009','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP010','PTP0010','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP011','PTP0011','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP012','PTP0012','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP013','PTP0013','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP014','PTP0014','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP015','PTP0015','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP016','PTP0016','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP018','PTP0018','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP019','PTP0019','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP020','PTP0020','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP021','PTP0021','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP022','PTP0022','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP024','PTP0024','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP025','PTP0025','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP026','PTP0026','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP027','PTP0027','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP028','PTP0028','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP029','PTP0029','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP030','PTP0030','1000');



INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP031','PTP0031','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP032','PTP0032','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP033','PTP0033','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP034','PTP0034','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP035','PTP0035','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP036','PTP0036','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP037','PTP0037','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP038','PTP0038','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP039','PTP0039','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP040','PTP0040','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP041','PTP0041','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP042','PTP0042','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP043','PTP0043','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP044','PTP0044','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP045','PTP0045','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP046','PTP0046','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP048','PTP0048','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP049','PTP0049','500');

INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP050','PTP0050','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP052','PTP0052','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP054','PTP0054','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP055','PTP0055','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP056','PTP0056','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP057','PTP0057','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP058','PTP0058','1000');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP059','PTP0059','500');
INSERT INTO CTPHIEUTHUEPHONG VALUES('CTPTP060','PTP0060','1000');

 ------------------DU LIEU PHIEUTHUEPHONG------------------------- 
INSERT INTO PHIEUTHUEPHONG VALUES('PTP001','KH001','P0001',
TO_DATE('2016-02-01','yyyy/mm/dd'),TO_DATE('2016-02-02','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP002','KH002','P0002',
TO_DATE('2016-02-02','yyyy/mm/dd'),TO_DATE('2016-02-03','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP003','KH003','P0003',
TO_DATE('2016-02-12','yyyy/mm/dd'),TO_DATE('2016-02-13','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP004','KH004','P0004',
TO_DATE('2016-02-13','yyyy/mm/dd'),TO_DATE('2016-02-14','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP005','KH005','P0005',
TO_DATE('2016-02-14','yyyy/mm/dd'),TO_DATE('2016-02-15','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP006','KH006','P0006',
TO_DATE('2016-02-15','yyyy/mm/dd'),TO_DATE('2016-02-16','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP007','KH007','P0007',
TO_DATE('2016-02-07','yyyy/mm/dd'),TO_DATE('2016-02-08','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP008','KH008','P0008',
TO_DATE('2016-02-08','yyyy/mm/dd'),TO_DATE('2016-02-09','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP009','KH009','P0009',
TO_DATE('2018-09-21','yyyy/mm/dd'),TO_DATE('2018-09-23','yyyy/mm/dd'));

INSERT INTO PHIEUTHUEPHONG VALUES('PTP0010','KH010','P00010',TO_DATE('2016-02-10','yyyy/mm/dd'),TO_DATE('2016-02-12','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0011','KH011','P00011',TO_DATE('2016-02-11','yyyy/mm/dd'),TO_DATE('2016-02-13','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0012','KH012','P00012',TO_DATE('2016-02-12','yyyy/mm/dd'),TO_DATE('2016-02-14','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0013','KH013','P00013',TO_DATE('2019-09-13','yyyy/mm/dd'),TO_DATE('2019-09-14','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0014','KH014','P00014',TO_DATE('2019-09-14','yyyy/mm/dd'),TO_DATE('2019-09-15','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0015','KH015','P00015',TO_DATE('2019-09-15','yyyy/mm/dd'),TO_DATE('2019-09-16','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0016','KH016','P00016',TO_DATE('2019-09-16','yyyy/mm/dd'),TO_DATE('2019-09-17','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0018','KH018','P00018',TO_DATE('2019-09-18','yyyy/mm/dd'),TO_DATE('2019-09-19','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0019','KH019','P00019',TO_DATE('2019-09-19','yyyy/mm/dd'),TO_DATE('2019-09-20','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0020','KH020','P00020',TO_DATE('2019-09-20','yyyy/mm/dd'),TO_DATE('2019-09-21','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0021','KH021','P00021',TO_DATE('2020-11-21','yyyy/mm/dd'),TO_DATE('2020-11-23','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0022','KH022','P00022',TO_DATE('2020-11-22','yyyy/mm/dd'),TO_DATE('2020-11-24','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0024','KH024','P00024',TO_DATE('2020-11-24','yyyy/mm/dd'),TO_DATE('2020-11-26','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0025','KH025','P00025',TO_DATE('2021-01-25','yyyy/mm/dd'),TO_DATE('2021-01-26','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0026','KH026','P00026',TO_DATE('2021-01-26','yyyy/mm/dd'),TO_DATE('2021-01-27','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0027','KH027','P00027',TO_DATE('2021-01-27','yyyy/mm/dd'),TO_DATE('2021-01-28','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0028','KH028','P00028',TO_DATE('2021-01-28','yyyy/mm/dd'),TO_DATE('2021-01-29','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0029','KH029','P00029',TO_DATE('2021-01-29','yyyy/mm/dd'),TO_DATE('2021-01-30','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0030','KH030','P00030',TO_DATE('2021-01-30','yyyy/mm/dd'),TO_DATE('2021-01-31','yyyy/mm/dd'));


INSERT INTO PHIEUTHUEPHONG VALUES('PTP0031','KH010','P00010',TO_DATE('2016-02-10','yyyy/mm/dd'),TO_DATE('2016-02-12','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0032','KH011','P00011',TO_DATE('2016-02-11','yyyy/mm/dd'),TO_DATE('2016-02-13','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0033','KH012','P00012',TO_DATE('2016-02-12','yyyy/mm/dd'),TO_DATE('2016-02-14','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0034','KH013','P00013',TO_DATE('2019-09-13','yyyy/mm/dd'),TO_DATE('2019-09-14','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0035','KH014','P00014',TO_DATE('2019-09-14','yyyy/mm/dd'),TO_DATE('2019-09-15','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0036','KH015','P00015',TO_DATE('2019-09-15','yyyy/mm/dd'),TO_DATE('2019-09-16','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0037','KH016','P00016',TO_DATE('2019-09-16','yyyy/mm/dd'),TO_DATE('2019-09-17','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0038','KH018','P00018',TO_DATE('2019-09-18','yyyy/mm/dd'),TO_DATE('2019-09-19','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0039','KH019','P00019',TO_DATE('2019-09-19','yyyy/mm/dd'),TO_DATE('2019-09-20','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0040','KH020','P00020',TO_DATE('2019-09-20','yyyy/mm/dd'),TO_DATE('2019-09-21','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0041','KH021','P00021',TO_DATE('2020-11-21','yyyy/mm/dd'),TO_DATE('2020-11-23','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0042','KH022','P00022',TO_DATE('2020-11-22','yyyy/mm/dd'),TO_DATE('2020-11-24','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0043','KH024','P00024',TO_DATE('2020-11-24','yyyy/mm/dd'),TO_DATE('2020-11-26','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0044','KH025','P00025',TO_DATE('2021-01-25','yyyy/mm/dd'),TO_DATE('2021-01-26','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0045','KH026','P00026',TO_DATE('2021-01-26','yyyy/mm/dd'),TO_DATE('2021-01-27','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0046','KH027','P00027',TO_DATE('2021-01-27','yyyy/mm/dd'),TO_DATE('2021-01-28','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0047','KH028','P00028',TO_DATE('2021-01-28','yyyy/mm/dd'),TO_DATE('2021-01-29','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0048','KH029','P00029',TO_DATE('2021-01-29','yyyy/mm/dd'),TO_DATE('2021-01-30','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0049','KH030','P00030',TO_DATE('2021-01-30','yyyy/mm/dd'),TO_DATE('2021-01-31','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0050','KH030','P00030',TO_DATE('2021-01-30','yyyy/mm/dd'),TO_DATE('2021-01-31','yyyy/mm/dd'));


INSERT INTO PHIEUTHUEPHONG VALUES('PTP0052','KH031','P00011',TO_DATE('2016-02-11','yyyy/mm/dd'),TO_DATE('2016-02-13','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0053','KH032','P00012',TO_DATE('2016-02-12','yyyy/mm/dd'),TO_DATE('2016-02-14','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0054','KH033','P00013',TO_DATE('2019-09-13','yyyy/mm/dd'),TO_DATE('2019-09-14','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0055','KH034','P00014',TO_DATE('2019-09-14','yyyy/mm/dd'),TO_DATE('2019-09-15','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0056','KH035','P00015',TO_DATE('2019-09-15','yyyy/mm/dd'),TO_DATE('2019-09-16','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0057','KH036','P00016',TO_DATE('2019-09-16','yyyy/mm/dd'),TO_DATE('2019-09-17','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0058','KH038','P00018',TO_DATE('2019-09-18','yyyy/mm/dd'),TO_DATE('2019-09-19','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0059','KH039','P00019',TO_DATE('2019-09-19','yyyy/mm/dd'),TO_DATE('2019-09-20','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0060','KH040','P00020',TO_DATE('2019-09-20','yyyy/mm/dd'),TO_DATE('2019-09-21','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0061','KH041','P00021',TO_DATE('2020-11-21','yyyy/mm/dd'),TO_DATE('2020-11-23','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0062','KH042','P00022',TO_DATE('2020-11-22','yyyy/mm/dd'),TO_DATE('2020-11-24','yyyy/mm/dd'));

INSERT INTO PHIEUTHUEPHONG VALUES('PTP0063','KH043','P00024',
TO_DATE('2020-11-24','yyyy/mm/dd'),TO_DATE('2020-11-26','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0064','KH045','P00025',
TO_DATE('2021-01-25','yyyy/mm/dd'),TO_DATE('2021-01-26','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0065','KH046','P00026',
TO_DATE('2021-01-26','yyyy/mm/dd'),TO_DATE('2021-01-27','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0066','KH047','P00027',
TO_DATE('2021-01-27','yyyy/mm/dd'),TO_DATE('2021-01-28','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0067','KH048','P00028',
TO_DATE('2021-01-28','yyyy/mm/dd'),TO_DATE('2021-01-29','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0068','KH049','P00029',
TO_DATE('2021-01-29','yyyy/mm/dd'),TO_DATE('2021-01-30','yyyy/mm/dd'));
INSERT INTO PHIEUTHUEPHONG VALUES('PTP0069','KH050','P00030',
TO_DATE('2021-01-30','yyyy/mm/dd'),TO_DATE('2021-01-31','yyyy/mm/dd'));


 ------------------DU LIEU LOAIPHONG------------------------- 
INSERT INTO LOAIPHONG VALUES('LP001','Phong tieu chuan');
INSERT INTO LOAIPHONG VALUES('LP002','Phong cao cap');
INSERT INTO LOAIPHONG VALUES('LP003','Phong thuong gia');
INSERT INTO LOAIPHONG VALUES('LP004','Phong tong thong');

-------------DU LIEU PHONG------------------
INSERT INTO PHONG VALUES('P0001','LP001','TTP01','1','1000000','Ngay');
INSERT INTO PHONG VALUES('P0002','LP002','TTP02','2','2000000','Ngay');
INSERT INTO PHONG VALUES('P0003','LP003','TTP03','1','4000000','Ngay');
INSERT INTO PHONG VALUES('P0004','LP004','TTP01','2','7000000','Ngay');
INSERT INTO PHONG VALUES('P0005','LP001','TTP01','1','1000000','Ngay');
INSERT INTO PHONG VALUES('P0006','LP002','TTP02','2','2000000','Ngay');
INSERT INTO PHONG VALUES('P0007','LP003','TTP03','1','4000000','Ngay');
INSERT INTO PHONG VALUES('P0008','LP004','TTP02','2','7000000','Ngay');
INSERT INTO PHONG VALUES('P0009','LP001','TTP03','1','1000000','Ngay');
INSERT INTO PHONG VALUES('P00010','LP002','TTP01','2','2000000','Ngay');
INSERT INTO PHONG VALUES('P00011','LP003','TTP02','1','4000000','Ngay');
INSERT INTO PHONG VALUES('P00012','LP004','TTP03','2','7000000','Ngay');
INSERT INTO PHONG VALUES('P00013','LP001','TTP01','2','1000000','Ngay');
INSERT INTO PHONG VALUES('P00014','LP002','TTP02','1','2000000','Ngay');
INSERT INTO PHONG VALUES('P00015','LP003','TTP01','2','4000000','Ngay');
INSERT INTO PHONG VALUES('P00016','LP004','TTP02','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00018','LP002','TTP03','2','2000000','Ngay');
INSERT INTO PHONG VALUES('P00019','LP003','TTP01','1','4000000','Ngay');

INSERT INTO PHONG VALUES('P00020','LP004','TTP02','2','7000000','Ngay');
INSERT INTO PHONG VALUES('P00021','LP001','TTP01','1','1000000','Ngay');
INSERT INTO PHONG VALUES('P00022','LP002','TTP02','2','2000000','Ngay');
INSERT INTO PHONG VALUES('P00023','LP003','TTP03','1','4000000','Ngay');
INSERT INTO PHONG VALUES('P00024','LP004','TTP03','2','7000000','Ngay');
INSERT INTO PHONG VALUES('P00025','LP001','TTP01','2','1000000','Ngay');
INSERT INTO PHONG VALUES('P00026','LP002','TTP01','1','2000000','Ngay');
INSERT INTO PHONG VALUES('P00027','LP003','TTP02','1','4000000','Ngay');
INSERT INTO PHONG VALUES('P00028','LP004','TTP03','2','7000000','Ngay');
INSERT INTO PHONG VALUES('P00029','LP001','TTP02','1','1000000','Ngay');
INSERT INTO PHONG VALUES('P00030','LP002','TTP03','2','2000000','Ngay');
INSERT INTO PHONG VALUES('P00031','LP003','TTP01','2','4000000','Ngay');
INSERT INTO PHONG VALUES('P00032','LP004','TTP02','1','7000000','Ngay');

INSERT INTO PHONG VALUES('P00033','LP001','TTP01','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00034','LP002','TTP02','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00035','LP003','TTP01','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00036','LP004','TTP02','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00037','LP001','TTP01','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00038','LP002','TTP02','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00039','LP003','TTP01','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00040','LP004','TTP02','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00041','LP001','TTP01','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00042','LP002','TTP02','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00043','LP003','TTP01','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00044','LP004','TTP02','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00045','LP001','TTP01','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00046','LP002','TTP02','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00047','LP003','TTP01','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00048','LP004','TTP02','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00049','LP001','TTP01','1','7000000','Ngay');
INSERT INTO PHONG VALUES('P00050','LP002','TTP02','1','7000000','Ngay');


-------------DU LIEU TINHTRANGPHONG------------------
INSERT INTO TINHTRANGPHONG VALUES('TTP01','Phong trong');
INSERT INTO TINHTRANGPHONG VALUES('TTP02','Phong da co nguoi dat');
INSERT INTO TINHTRANGPHONG VALUES('TTP03','Phong da co nguoi o');


-------------DU LIEU DICHVU------------------
INSERT INTO DICHVU VALUES ('DV001','GUI','Giat ui');
INSERT INTO DICHVU VALUES ('DV002','KAO','Karaoke');
INSERT INTO DICHVU VALUES ('DV003','DUA','Thue Xe Dua Don');
INSERT INTO DICHVU VALUES ('DV004','NHA','Nha Hang');
INSERT INTO DICHVU VALUES ('DV005','SPA','SPA');
INSERT INTO DICHVU VALUES ('DV006','GYM','Phong Tap Gym');
INSERT INTO DICHVU VALUES ('DV007','HOP','Thue Phong Hop');
INSERT INTO DICHVU VALUES ('DV008','BAR','Thue Phong Bar');


-------------DU LIEU LOAIDICHVU------------------
INSERT INTO LOAIDICHVU VALUES('GUI',100000,TO_DATE('2019/01/07','yyyy/mm/dd'));--Giatui
INSERT INTO LOAIDICHVU VALUES('KAO',1000000,TO_DATE('2019/01/02','yyyy/mm/dd'));--Karaoke
INSERT INTO LOAIDICHVU VALUES('DUA',500000,TO_DATE('2019/09/12','yyyy/mm/dd'));--Xeduadon
INSERT INTO LOAIDICHVU VALUES('NHA',2500000,TO_DATE('2019/11/26','yyyy/mm/dd'));--Nhahang
INSERT INTO LOAIDICHVU VALUES('SPA',1500000,TO_DATE('2019/12/31','yyyy/mm/dd'));--SPA
INSERT INTO LOAIDICHVU VALUES('GYM',700000,TO_DATE('2019/09/04','yyyy/mm/dd'));-- thue phong tap gym
INSERT INTO LOAIDICHVU VALUES('HOP',1200000,TO_DATE('2019/08/11','yyyy/mm/dd'));--Thue phong hop
INSERT INTO LOAIDICHVU VALUES('BAR',1100000,TO_DATE('2019/03/09','yyyy/mm/dd'));--Thue quay bar

-------------DU LIEU VATTU------------------
INSERT INTO VATTU VALUES ('VT01','Dien Thoai');
INSERT INTO VATTU VALUES ('VT02','May say toc');
INSERT INTO VATTU VALUES ('VT03','Nuoc ngot');
INSERT INTO VATTU VALUES ('VT04','Banh ngot');
INSERT INTO VATTU VALUES ('VT05','O cam dien');
INSERT INTO VATTU VALUES ('VT06','Gia de hanh ly');
INSERT INTO VATTU VALUES ('VT07','Tham trai buong ngu');


-------------DU LIEU CTVATTU------------------

INSERT INTO CTVATTU VALUES ('VT01','P0001','2');
INSERT INTO CTVATTU VALUES ('VT02','P0002','1');
INSERT INTO CTVATTU VALUES ('VT01','P0003','2');
INSERT INTO CTVATTU VALUES ('VT02','P0004','3');
INSERT INTO CTVATTU VALUES ('VT04','P0006','1');
INSERT INTO CTVATTU VALUES ('VT03','P0007','6');
INSERT INTO CTVATTU VALUES ('VT04','P0008','7');
INSERT INTO CTVATTU VALUES ('VT01','P0009','8');
INSERT INTO CTVATTU VALUES ('VT02','P00010','2');
INSERT INTO CTVATTU VALUES ('VT03','P00011','2');
INSERT INTO CTVATTU VALUES ('VT01','P00012','6');
INSERT INTO CTVATTU VALUES ('VT02','P00013','6');
INSERT INTO CTVATTU VALUES ('VT03','P00014','3');
INSERT INTO CTVATTU VALUES ('VT04','P00015','4');
INSERT INTO CTVATTU VALUES ('VT02','P00016','4');
INSERT INTO CTVATTU VALUES ('VT03','P00017','2');
INSERT INTO CTVATTU VALUES ('VT04','P00018','1');
INSERT INTO CTVATTU VALUES ('VT02','P00020','3');
INSERT INTO CTVATTU VALUES ('VT03','P00021','4');
INSERT INTO CTVATTU VALUES ('VT01','P00023','1');
INSERT INTO CTVATTU VALUES ('VT01','P00024','2');
INSERT INTO CTVATTU VALUES ('VT02','P00025','3');
INSERT INTO CTVATTU VALUES ('VT03','P00026','4');
INSERT INTO CTVATTU VALUES ('VT04','P00027','1');
INSERT INTO CTVATTU VALUES ('VT01','P00028','2');
INSERT INTO CTVATTU VALUES ('VT01','P00029','1');
INSERT INTO CTVATTU VALUES ('VT02','P00030','2');
INSERT INTO CTVATTU VALUES ('VT03','P00031','3');
INSERT INTO CTVATTU VALUES ('VT04','P00032','4');

INSERT INTO CTVATTU VALUES ('VT02','P0001','4');
INSERT INTO CTVATTU VALUES ('VT03','P0001','4');
INSERT INTO CTVATTU VALUES ('VT04','P0001','4');
INSERT INTO CTVATTU VALUES ('VT05','P0001','4');
INSERT INTO CTVATTU VALUES ('VT06','P0001','4');
INSERT INTO CTVATTU VALUES ('VT07','P0001','4');
INSERT INTO CTVATTU VALUES ('VT01','P0002','4');
INSERT INTO CTVATTU VALUES ('VT02','P0002','4');
INSERT INTO CTVATTU VALUES ('VT03','P0002','4');
INSERT INTO CTVATTU VALUES ('VT04','P0002','4');
INSERT INTO CTVATTU VALUES ('VT05','P0002','4');
INSERT INTO CTVATTU VALUES ('VT06','P0002','4');
INSERT INTO CTVATTU VALUES ('VT07','P0002','4');


INSERT INTO CTVATTU VALUES ('VT02','P0004','4');
INSERT INTO CTVATTU VALUES ('VT03','P0004','4');
INSERT INTO CTVATTU VALUES ('VT04','P0004','4');
INSERT INTO CTVATTU VALUES ('VT05','P0004','4');
INSERT INTO CTVATTU VALUES ('VT06','P0004','4');
INSERT INTO CTVATTU VALUES ('VT07','P0004','4');
INSERT INTO CTVATTU VALUES ('VT01','P0003','4');
INSERT INTO CTVATTU VALUES ('VT02','P0003','4');
INSERT INTO CTVATTU VALUES ('VT03','P0003','4');
INSERT INTO CTVATTU VALUES ('VT04','P0003','4');
INSERT INTO CTVATTU VALUES ('VT05','P0003','4');
INSERT INTO CTVATTU VALUES ('VT06','P0003','4');
INSERT INTO CTVATTU VALUES ('VT07','P0003','4');

INSERT INTO CTVATTU VALUES ('VT02','P0005','4');
INSERT INTO CTVATTU VALUES ('VT03','P0005','4');
INSERT INTO CTVATTU VALUES ('VT04','P0005','4');
INSERT INTO CTVATTU VALUES ('VT05','P0005','4');
INSERT INTO CTVATTU VALUES ('VT06','P0005','4');
INSERT INTO CTVATTU VALUES ('VT07','P0005','4');
INSERT INTO CTVATTU VALUES ('VT01','P0006','4');
INSERT INTO CTVATTU VALUES ('VT02','P0006','4');
INSERT INTO CTVATTU VALUES ('VT03','P0006','4');
INSERT INTO CTVATTU VALUES ('VT04','P0006','4');
INSERT INTO CTVATTU VALUES ('VT05','P0006','4');
INSERT INTO CTVATTU VALUES ('VT06','P0006','4');
INSERT INTO CTVATTU VALUES ('VT07','P0006','4');

INSERT INTO CTVATTU VALUES ('VT02','P0007','4');
INSERT INTO CTVATTU VALUES ('VT03','P0007','4');
INSERT INTO CTVATTU VALUES ('VT04','P0007','4');
INSERT INTO CTVATTU VALUES ('VT05','P0007','4');
INSERT INTO CTVATTU VALUES ('VT06','P0007','4');
INSERT INTO CTVATTU VALUES ('VT07','P0007','4');
INSERT INTO CTVATTU VALUES ('VT01','P0008','4');
INSERT INTO CTVATTU VALUES ('VT02','P0008','4');
INSERT INTO CTVATTU VALUES ('VT03','P0008','4');
INSERT INTO CTVATTU VALUES ('VT04','P0008','4');
INSERT INTO CTVATTU VALUES ('VT05','P0008','4');
INSERT INTO CTVATTU VALUES ('VT06','P0008','4');
INSERT INTO CTVATTU VALUES ('VT07','P0008','4');

INSERT INTO CTVATTU VALUES ('VT02','P0009','4');
INSERT INTO CTVATTU VALUES ('VT03','P0009','4');
INSERT INTO CTVATTU VALUES ('VT04','P0009','4');
INSERT INTO CTVATTU VALUES ('VT05','P0009','4');
INSERT INTO CTVATTU VALUES ('VT06','P0009','4');
INSERT INTO CTVATTU VALUES ('VT07','P0009','4');
INSERT INTO CTVATTU VALUES ('VT01','P0009','4');
INSERT INTO CTVATTU VALUES ('VT02','P00010','4');
INSERT INTO CTVATTU VALUES ('VT03','P00010','4');
INSERT INTO CTVATTU VALUES ('VT04','P00010','4');
INSERT INTO CTVATTU VALUES ('VT05','P00010','4');
INSERT INTO CTVATTU VALUES ('VT06','P00010','4');
INSERT INTO CTVATTU VALUES ('VT07','P00010','4');

INSERT INTO CTVATTU VALUES ('VT02','P00011','4');
INSERT INTO CTVATTU VALUES ('VT03','P00011','4');
INSERT INTO CTVATTU VALUES ('VT04','P00011','4');
INSERT INTO CTVATTU VALUES ('VT05','P00011','4');
INSERT INTO CTVATTU VALUES ('VT06','P00011','4');
INSERT INTO CTVATTU VALUES ('VT07','P00011','4');
INSERT INTO CTVATTU VALUES ('VT01','P00011','4');
INSERT INTO CTVATTU VALUES ('VT02','P00012','4');
INSERT INTO CTVATTU VALUES ('VT03','P00012','4');
INSERT INTO CTVATTU VALUES ('VT04','P00012','4');
INSERT INTO CTVATTU VALUES ('VT05','P00012','4');
INSERT INTO CTVATTU VALUES ('VT06','P00012','4');
INSERT INTO CTVATTU VALUES ('VT07','P00012','4');



select * from phong
  
--- viet 10 cau lenh cap nhat va xoa du lieu lien quan den nghiep vu
-- viet toi thieu 30 cau truy van lien quan den nghiep vu ?Ã£ ch?n
-- 6 view 6 func, 6 proc. 4 trigger

select * 
from dichvu;
select * 
from hihi;

create public synonym hihi for dichvu;
-- ?NG D?NG
-- ph?n 1 [SYNONYM]
--1.1. T?O M?T SYNONYM NG?N G?N ?? D? DÃ€NG G?I TRONG B?NG KHÃ?CH HÃ€NG
CREATE PUBLIC SYNONYM KHAN FOR KHACHHANG;

--1.2. T?O TÃŠN ??NG NGH?A NG?N G?N CHO VIEW S? L??NG KHÃ?CH HÃ€NG

-- PH?N 2 [INDEX]
-- INDEX ??N
-- 2.1. T?O "INDEX" CHO B?NG D?CH V?
CREATE INDEX INDEX_DICHVU
ON DICHVU (MALOAIDICHVU);

-- XEM L?I CÃ?C INDEX CÃ“ TRONG TABLE D?CH V?
SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'DICHVU';
-- CÃ?CH KI?M TRA CÃ‚U TRUY V?N CÃ“ S? D?NG INDEX HAY KHÃ”NG TA TH?C HI?N THÃŠM EXPLAIN PLAN FOR VÃ€O TR??C CÃ‚U TRUY V?N

EXPLAIN PLAN FOR
SELECT * 
FROM DICHVU
WHERE MALOAIDICHVU = 'GUI'

--Sau ?Ã³, s? d?ng theprocedure ?? hi?n th? n?i dung c?a:DBMS_XPLAN.DISPLAY()plan_table
SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());

-- INDEX DOI
--https://www.oracletutorial.com/oracle-index/oracle-create-index/

CREATE INDEX INDEX_NHANVIEN
ON NHANVIEN(HONV,TENNV);

SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'NHANVIEN';

select * from nhanvien

SELECT * 
FROM nhanvien
WHERE honv LIKE 'T%' 
    AND tennv LIKE 'D%';

SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());
    
--- synonym

create synonym KHang for KHACHHANG

select * 
from KHang

--vw_doanhthunhanviencaonhat

create synonym top1doanhthu for vw_doanhthunhanviencaonhat

select *
from top1doanhthu

-- PHAN 3 VIEW
-- 3.1 T?o view danh sách nhân viên theo ch?c v? và b? ph?n 
-- (vw_dsnhanvien_theochucvu_bophan) g?m: Mã nhân viên,
-- h? tên nhân viên,gi?i tính, ngày sinh, tên b? ph?n, tên ch?c v?
-- (View c? b?n)

-- View c? b?n                                                     
CREATE or replace  VIEW vw_dsnhanvien_theochucvu_bophan
as
    Select  MaNv , HoNv , TenNv,
    GioiTinh, NgaySinh,TenBoPhan , TenChucVu
    From NhanVien NV 
    join ChucVu CV 
        on NV.MaChucVu = CV.MaChucVu
    join BoPhan BP 
        on BP.MaBoPhan = NV.MaBoPhan;
        
        
-- Thuc thi
select * 
from vw_dsnhanvien_theochucvu_bophan;


--3.2 Tao View danh sÃ¡ch so nhÃ¢n viÃªn cua tung bo phan (vw_ SoNhanVienMoiBoPhan) gom:
-- Ma bo phan, tÃªn bo phan, so luong nhÃ¢n viÃªn, ngÃ y thÃ nh lap.
--view gom nhÃ³m

-- view gom nhóm
CREATE OR REPLACE VIEW vw_SoNhanVienMoiBoPhan 
AS
    SELECT BP.MaBoPhan, TenBoPhan ,COUNT(MaNv) AS SLNV , NgayThanhLap
    from NhanVien NV 
    join BoPhan BP 
    on NV.MaBoPhan = BP.MaBoPhan
    group by BP.MaBoPhan, TenBoPhan  , NgayThanhLap;
    
    
-- Th?c thi
select * 
from vw_SoNhanVienMoiBoPhan;

--3.3 T?o View th?ng kê danh sách s? l??ng khách hàng VIP(vw_ soluongkhachvip) g?m:
-- Mã khách hàng, H? tên khách hàng, tên lo?i khách hàng
-- View th?ng kê

-- View th?ng kê
CREATE OR REPLACE VIEW vw_soluongkhachvip
as 
    select MaKh, HoKh, TenKh, TenLoaiKhachHang, GioiTinh
    from KhachHang KH 
    join LoaiKhachHang LKH 
        on KH.MaLoaiKhachHang = LKH.MaLoaiKhachHang
    where  LKH.MaLoaiKhachHang = 'LKH02';
    
-- Thuc thi
SELECT  *
from vw_soluongkhachvip;


select * from nhanvien;

--3.4 T?o View (vw_doanhthunhanviencaonhat) cho bi?t doanh thu c?a nhân viên có l??ng cao nh?t g?m: 
-- Mã nhân viên, h? và tên nhân viên, t?ng doanh thu c?a nhân viên. 
-- View truy v?n l?ng
-------------------------------------------------------L?I------------------------------------------------------------------------

-- View truy v?n l?ng
CREATE OR REPLACE VIEW vw_doanhthunhanviencaonhat
as
   select NV.MANV, NV.HONV, NV.TENNV  ,  sum( (ngaytraphong - ngaythuephong) * giaphong) as doanhthu
    from NhanVien NV
    join HOADON HD 
        ON NV.manv= hd.manv 
    join ctphieuthuephong ctpt 
        on ctpt.mactphieuthuephong = hd.mactphieuthuephong
    join phieuthuephong ptp 
        on ptp.maphieuthuephong = ctpt.maphieuthuephong
    join phong 
        on phong.maphong = ptp.maphong
    group by  NV.MANV, NV.HONV, NV.TENNV
    having  sum ((ngaytraphong - ngaythuephong) * giaphong) = 
                ( select  sum ( (ngaytraphong - ngaythuephong) * giaphong) 
                from NhanVien NV
                join HOADON HD 
                   ON NV.manv= hd.manv 
                join ctphieuthuephong ctpt 
                   on ctpt.mactphieuthuephong = hd.mactphieuthuephong
                join phieuthuephong ptp 
                   on ptp.maphieuthuephong = ctpt.maphieuthuephong
                join phong 
                   on phong.maphong = ptp.maphong
                group by  NV.MANV, NV.HONV, NV.TENNV 
                order by sum ( (ngaytraphong - ngaythuephong) * giaphong) desc 
                fetch first 1 rows only) ;

-- Thuc thi
select * from vw_doanhthunhanviencaonhat;


-- 1.0 View case when
-- T?o view cho phép xem thông tin khách hàng bao g?m: Mã khách hàng, H? tên, 
-- ??n giá, và phân lo?i khách hàng(Vãng lai, th??ng, ti?m n?ng) d?a trên ??n giá hóa ??n c?a m?i khách

-- View Case when
CREATE OR REPLACE VIEW vw_phanloaikhachhang
AS
SELECT kh.makh, hokh, tenkh,  sum( (ngaytraphong - ngaythuephong) * giaphong) AS GIA
,   case 
        when  sum((ngaytraphong - ngaythuephong) * giaphong) < 1000000 then 'Khach hang vang lai'
        when  sum((ngaytraphong - ngaythuephong) * giaphong) >= 1000000 
            and sum((ngaytraphong - ngaythuephong) * giaphong) <= 10000000  then 'Khach hang thuong'
        when  sum((ngaytraphong - ngaythuephong) * giaphong) > 10000000 then 'Khach hang VIP'
    end AS LOAIKH
FROM khachhang KH
join phieuthuephong ptp
    on kh.makh = ptp.makh 
join phong p
    on p.maphong = ptp.maphong
group by  kh.makh, hokh, tenkh;

-- Thu thi
select * 
from vw_phanloaikhachhang;

-- 2.0 “C?p nh?t d? li?u tr?c ti?p vào view v?i khách hàng có gi?i tính N?”

CREATE OR REPLACE VIEW vw_khachhangnu
AS
SELECT *
FROM KhachHang 
WHERE GioiTinh LIKE N'Nu';

-- xem view

SELECT *
FROM vw_khachhangnu;

-- th?c thi
SELECT *
FROM LoaiKhachHang;

UPDATE vw_khachhangnu
SET MaLoaiKhachHang = 'LKH01'
WHERE MaKh = 'KH014';

--2.2 View t?o view Update mã chi ti?t hóa ??n trong b?ng hóa ??n ---------------------------------- ORACLE KHÔNG UPDATE VIEW ???C

CREATE OR REPLACE VIEW vw_windowfunction
AS
    SELECT maphong, sogiuong, giaphong, donvitinh,
    RANK() OVER (PARTITION BY sogiuong ORDER BY giaphong DESC) as rak
    FROM PHONG;
    
-- Xem view
SELECT *
FROM vw_windowfunction;

-- th?c thi
UPDATE vw_windowfunction
SET giaphong = 70000000
WHERE maphong = 'P0016';

--3.0 Insert View “Thêm d? li?u tr?c ti?p vào view ???c t?o v?i thông tin: Mã nhân viên, H? nhân viên, Tên nv, 
-- Gi?i tính, Ngày sinh v?i ?i?u ki?n ngày sinh ph?i khác NULL”

CREATE OR REPLACE VIEW vw_Nhanvien
AS
SELECT MaNv, HoNv, TenNv, GioiTinh,NgaySinh
FROM NhanVien
WHERE NgaySinh is not null;

SELECT *
FROM vw_Nhanvien;

-- Th?c thi
INSERT INTO vw_Nhanvien 
VALUES('NV051',N'Ho Quoc',N'?at','Nam', TO_DATE('2002/10/12','yyyy/mm/dd'));


-- 3.1 L?i view v?i check option(ki?m tra ?i?u ki?n trong m?nh ?? where)
CREATE OR REPLACE VIEW vw_Khachhang
AS
    SELECT MaKh, HoKh, TenKh,GioiTinh,CMND
    FROM KhachHang
    WHERE CMND IS NOT NULL
    WITH CHECK OPTION

SELECT * 
FROM vw_Khachhang

INSERT INTO vw_Khachhang
VALUES('KH052','H? Nguy?n','An','Nam',NULL)

INSERT INTO vw_Khachhang
VALUES('KH0052','H? Nguy?n','An','Nam','79202023839')

set serveroutput on
---------------- PROC
-- 4.1 T?o th? t?c cho bi?t s? l??ng phòng theo mã lo?i phòng
-- (th? t?c không có tham s?)

-- 44.	T?o th? t?c có tên là dept_info cho bi?t thông tin v? phòng ban v?i tham s? truy?n vào là mã phòng ban.
-- 1 tham s?
-- t?o th? t?c có tên xxxxx cho bi?t thông tin c?a phòng hi?n t?i v?i tham s? truy?n vào là mã phong ban

CREATE OR REPLACE PROCEDURE sp_thongtinphong (v_maphong varchar2)
as
    sl varchar2 (20);
    begin
        select sogiuong into sl
        from phong
        where maphong = v_maphong;
        
        dbms_output.put_line ('Phong '||v_maphong ||' co '||sl||' giuong');
        
        exception when no_data_found
            THEN dbms_output.put_line ('Khong co ma phong nay');  
    end;


-- Th?c thi
execute sp_thongtinphong ('P0001')


CREATE OR REPLACE PROCEDURE sp_thongtindichvu (v_madv varchar2)
as
    tendv varchar2 (20);
    begin
        select tendichvu into tendv
        from dichvu
        where madichvu = v_madv;
        
        dbms_output.put_line ('Ma dich vu '||v_madv ||' la: '||tendv);
        
        exception when no_data_found
            THEN dbms_output.put_line ('Khong co ma dich vu nay');  
    end;


execute sp_thongtindichvu ('DV002')


select * from dichvu;
set serveroutput on
-- t?o th? t?c không có tham s? truy?n vào
-- t?o th? t?c tìm ra phòng có giá cao nh?t

create or replace procedure sp_find
as
    cursor c_phong
    is
    select maphong, maloaiphong, sogiuong, giaphong
    from phong
    where giaphong in (select giaphong
                        from phong
                        order by giaphong desc
                        fetch first 1 rows only);
v_maphong phong.maphong%type;
v_maloaiphong phong.maloaiphong%type;
v_sogiuong phong.sogiuong%type;
v_giaphong phong.giaphong%type;
begin 
    for r_phong in c_phong
    loop
        v_maphong := r_phong.maphong;
        v_maloaiphong := r_phong.maloaiphong;
        v_sogiuong := r_phong.sogiuong;
        v_giaphong := r_phong.giaphong;

        dbms_output.put_line('Maphong: '||v_maphong||' 
        - maloaiphong: '|| v_maloaiphong||'  - sogiuong: '
        || v_sogiuong||' - giaphong: '|| v_giaphong );
    end loop;
end;

set serveroutput on;

execute sp_find;
    

--47.	T?o th? t?c có tên là sp_add_dv thêm m?t D?CH V? m?i v?i t?t c? các giá tr? là tham s? truy?n vào. 

CREATE OR REPLACE PROCEDURE sp_add_dv (v_madichvu varchar2, 
                            v_maloaidichvu varchar2, v_tendichvu varchar2)
as
    v_madichvu_tmp varchar2 (20) ;
    v_error exception;
    begin
        select madichvu into v_madichvu_tmp
        from dichvu
        where madichvu = v_madichvu;
        
        if v_madichvu_tmp is not null 
        then raise v_error;
        end if;
        
        exception when v_error 
        then dbms_output.put_line ('Khong the them vi da co ma dich vu nay');
        
        when no_data_found then
            INSERT INTO DICHVU (madichvu, maloaidichvu, tendichvu)
            VALUES (v_madichvu,v_maloaidichvu,v_tendichvu);
            dbms_output.put_line ('du lieu da duoc them');
    end;

execute sp_add_dv ('DV009','COM','Com que');

select * from dichvu 
    
--46.	T?o th? t?c có tên là update_comm  c?p nh?t hoa h?ng cho nhân viên t?ng thêm 5% hoa h?ng ban ??u, tham s? truy?n vào là mã nhân viên. 

CREATE OR REPLACE PROCEDURE sp_update_phong (v_maphong varchar2)
as
    v_maphong_tmp varchar2 (20) ;
    v_error exception;
    begin
        select maphong into v_maphong_tmp
        from phong
        where maphong = v_maphong;
        
        if v_maphong_tmp is not null 
        then 
            update phong
            set giaphong = giaphong * 1.05
            where maphong = v_maphong;
            dbms_output.put_line('update du lieu thanh cong');
        end if;
        
        exception 
        when no_data_found then           
            dbms_output.put_line ('Khong the cap nhat du lieu vi khong co ma phong nay');    
    end;

execute sp_update_phong ('P0001');

select * from phong;


-- câu 5
--48.	T?o th? t?c có tên là delete_emp xóa m?t nhân viên m?i v?i mã nhân viên là tham s? truy?n vào. 

CREATE OR REPLACE PROCEDURE sp_delete_nhanvien (v_manv varchar2)
as
    v_manvn_tmp varchar2 (20) ;
    v_error exception;
    begin
        select manv into v_manvn_tmp
        from nhanvien
        where manv = v_manv;
        
        if v_manvn_tmp is not null 
        then 
            delete nhanvien
            where manv = v_manv;
            dbms_output.put_line('xoa du lieu thanh cong');
        end if;
        
        exception 
        when no_data_found 
        then           
            dbms_output.put_line ('Khong the xoa du lieu vi khong co nhan vien nay');    
    end;

select * from nhanvien;

execute sp_delete_nhanvien ('NV0050')


  INSERT  INTO NHANVIEN (MANV, MACHUCVU, MABOPHAN, HONV,TENNV, GIOITINH, NGAYSINH, DIACHI,DIENTHOAI,EMAIL) VALUES ('NV0050','CV03','BP08',N'Le',N'Mo',N'Nu',TO_DATE('1986/08/28','yyyy/mm/dd'),'34 ap Chien Luoc TP HCM','0712387421','lemo@gmail.com');
 
-- câu 6 t??ng t? 9.10 bt nhóm



------------------ FUNCTION

-- 5.1 T?o Function tinh so luong hoa don c?a t?ng nhân viên

CREATE OR REPLACE FUNCTION func_slhoadon_nv (v_manv in varchar2)
return number
as
    v_tmp varchar2 (20);
    v_sl number;
    v_loi exception;
    begin 
        select manv into v_tmp
        from nhanvien
        where manv = v_manv;
        
        if v_tmp is not null
            then
                select count(hd.mahoadon) into v_sl
                from nhanvien nv
                join hoadon hd
                    on nv.manv = hd.manv
                group by nv.manv
                having nv.manv = v_manv;
        end if ;
        return v_sl;
    exception   
        when no_data_found
            then 
                DBMS_output.put_line ('Khong co du lieu');     
            return 0;
    end;

execute DBMS_output.put_line('Tong so luong hoa don: '||func_slhoadon_nv('NV0001'));   --//&maphong

-- câu 2    
-- t?o hàm có tên xxx cho bi?t tên d?ch v? v?i mã d?ch v? là tham s? truy?n vào

CREATE OR REPLACE FUNCTION func_dv (v_madichvu in varchar2)
return varchar2
as
    v_tendv varchar2 (100);
    begin
        select tendichvu into v_tendv
        from dichvu
        where madichvu = v_madichvu;

        return v_tendv;
        
        exception 
            when no_data_found 
            then return ('Du lieu khong tim thay');
            when others then
            return ('loi ham');
    end;

execute DBMS_output.put_line ('Ten dich vu la: '||func_dv ('DV001'));

select * from dichvu;

-- xuât hàm ki?u new 

declare tmp varchar2 (100);
begin
    tmp := func_dv ('&madv');
    DBMS_output.put_line ('ten dich vu la: '||tmp);
end;

set serveroutput on;


CREATE OR REPLACE FUNCTION func_vattu (v_mavattu in varchar2)
return varchar2
as
    v_tenvattu varchar2 (100);
    begin
        select tenvattu into v_tenvattu
        from vattu
        where mavattu = v_mavattu;

        return v_tenvattu;
        
        exception 
            when no_data_found 
            then return ('Du lieu khong tim thay');
            when others then
            return ('loi ham');
    end;

execute DBMS_output.put_line ('Ten vat tu la: '||func_vattu ('VT01'));


select * from vattu
        
-- câu 3

-- th?ng kê s? ti?n hóa ??n trong kho?ng th?i gian t? ngày ?ên ngày thuê phòng 

CREATE OR REPLACE FUNCTION func_money (tungay in varchar2, denngay in varchar2)
return number
as
    v_gia number;
    begin
        select sum((ngaytraphong - ngaythuephong) * giaphong) into v_gia
        from hoadon hd 
        join CTPHIEUTHUEPHONG CTPT
            on hd.mactphieuthuephong = ctpt.mactphieuthuephong
        join phieuthuephong ptp 
            on ptp.maphieuthuephong = ctpt.maphieuthuephong
        join phong 
            on phong.maphong = ptp.maphong
        where ngaythuephong between tungay and denngay;
        
        return v_gia;
        
        exception 
            when no_data_found 
            then return ('Du lieu khong tim thay');
            when others then
            return ('loi ham');
    end;

execute DBMS_output.put_line ('Tong so tien la: '||func_money ('15-FEB-16','21-SEP-18'));

-- hàm ki?m tra

select   sum((ngaytraphong - ngaythuephong) * giaphong) as gia, ngaythuephong
from hoadon hd 
join CTPHIEUTHUEPHONG CTPT
    on hd.mactphieuthuephong = ctpt.mactphieuthuephong
join phieuthuephong ptp 
    on ptp.maphieuthuephong = ctpt.maphieuthuephong
join phong 
    on phong.maphong = ptp.maphong
group by ngaythuephong
order by ngaythuephong;



-- câu 4 
-- t?o hàm cho bi?t khách hàng là khách vãng lai khách th??ng hay khách vip v?i tham s? truy?n vào là mã nhân viên

CREATE OR REPLACE FUNCTION func_phanloaikh (v_makh in varchar2)
return varchar2
as
    v_loaikh varchar2 (150);
    begin
        SELECT case 
                when  sum((ngaytraphong - ngaythuephong) * giaphong) < 1000000 
                        then 'Khach hang vang lai'
                when  sum((ngaytraphong - ngaythuephong) * giaphong) >= 1000000 
                    and sum((ngaytraphong - ngaythuephong) * giaphong) <= 10000000  
                        then 'Khach hang thuong'
                when  sum((ngaytraphong - ngaythuephong) * giaphong) > 10000000 
                        then 'Khach hang VIP'
                end into v_loaikh
        FROM khachhang KH
        join phieuthuephong ptp
            on kh.makh = ptp.makh 
        join phong p
            on p.maphong = ptp.maphong
        group by  kh.makh
        having kh.makh = v_makh;

        return v_loaikh;
        
        exception  
            when no_data_found
            then return ('Du lieu khong tim thay');
            when others then
            return ('loi ham');
    end;
    

execute DBMS_output.put_line ('Khách hang thuoc loai: '||func_phanloaikh ('KH009'));

-- hàm ki?m tra
SELECT kh.makh, hokh, tenkh,  sum( (ngaytraphong - ngaythuephong) * giaphong) AS GIA
,   case 
        when  sum((ngaytraphong - ngaythuephong) * giaphong) < 1000000 then 'Khach hang vang lai'
        when  sum((ngaytraphong - ngaythuephong) * giaphong) >= 1000000 
            and sum((ngaytraphong - ngaythuephong) * giaphong) <= 10000000  then 'Khach hang thuong'
        when  sum((ngaytraphong - ngaythuephong) * giaphong) > 10000000 then 'Khach hang VIP'
    end AS LOAIKH
FROM khachhang KH
join phieuthuephong ptp
    on kh.makh = ptp.makh 
join phong p
    on p.maphong = ptp.maphong
group by  kh.makh, hokh, tenkh
having kh.makh = 'KH009';

-- câu 5
-- vi?t hàm t?ng giá phòng lên khi mua noel ??n vì nâng cao d?ch v? t?ng giá phòng t?ng th?ng

select  giaphong * 1.05
from phong p
join loaiphong lp
    on p.maloaiphong = lp.maloaiphong
where lp.maloaiphong = 'LP004';


CREATE OR REPLACE FUNCTION func_tanggiatien (v_maphong varchar2)
return number
as
    v_gianew number;
    begin
        select (giaphong * 1.05) into v_gianew
        from phong p
        join loaiphong lp
            on p.maloaiphong = lp.maloaiphong
        where maphong = v_maphong;
        
        return v_gianew;
        
        exception  
            when no_data_found
            then return ('Du lieu khong tim thay');
            when others then
            return ('loi ham');
    end;
    
execute DBMS_output.put_line ('Tien phong sau khi cap nhat la: '||func_tanggiatien ('P00021'));

select giaphong
from phong p
join loaiphong lp
    on p.maloaiphong = lp.maloaiphong
where 
order by lp.maloaiphong



 select (giaphong * 1.05)
        from phong p
        join loaiphong lp
            on p.maloaiphong = lp.maloaiphong
        where lp.maloaiphong = 'LP004';



--------- trigger 
--62.	Cài ??t ràng bu?c toàn v?n min_salary  luôn nh? h?n max_salary khi thêm m?i ho?c c?p nh?t thông tin b?ng công vi?c 
-- cài ??t ràng bu?c cho ngày thuê phòng luôn l?n h?n ho?c b?ng ngày ??t phòng

create or replace trigger tr_ngaydat
before insert or update
on phieuthuephong
for each row
    begin 
        if (:new.ngaythuephong > :new.ngaytraphong) then
            raise_application_error (-20022, 'Ngay tra phong nhap vao khong hop le');
        end if ;
    end;

select * from phieuthuephong

update phieuthuephong
set ngaytraphong = '06-FEB-16'
where maphieuthuephong = 'PTP002'



-- câu 2
-- cài ??t ràng buocj cho giá phòng t?ng ch? không gi?m

create or replace trigger tr_giaphong
before update
on phong
for each row
    begin 
        if (:new.giaphong < :old.giaphong) then
            raise_application_error (-20022, 'Gia phong moi phai lon hon gia phong cu');
        end if ;
    end;

select * from phong

update phong
set giaphong = '1103500'
where maphong = 'P0001'

-- câu 3 ----- h?i lag
-- cài ??t ngày l?p hóa ??n ph?i l?n h?n ho?c b?ng ngày hi?n t?i

create or replace trigger tr_ngaylaphoadon
before insert or update
on hoadon
for each row
    begin 
        if (:new.ngaylaphoadon <= sysdate) then
            raise_application_error (-20022, 
            'Ngay lap hoa don phai lon hon hoac bang ngay hien tai');
        end if ;
    end;

select * from hoadon

update hoadon 
set ngaylaphoadon = '09-DEC-22' 
where mahoadon = 'HD0031'


select sysdate
from nhanvien

-- câu 4
-- t?o trigger cho s? giuong trong phong phai l?n hon b?ng 0

create or replace trigger tr_sogiuong
before insert or update
on phong
for each row
    begin 
        if (:new.sogiuong <= 0) then
            raise_application_error (-20022, 'So giuong phai lon hon 0');
        end if ;
    end;

select * from phong

update phong
set sogiuong = 1
where maphong ='P0001'



----------------------------------- 30 cau truy v?n
--câu 1: cho bi?t thông tin c?a nhân viên v?i 

select nv.manv, honv, tennv, gioitinh, ngaysinh, 
diachi, dienthoai, email, tenchucvu, tenbophan
from nhanvien nv
join chucvu cv
    on nv.Machucvu = cv.machucvu
join bophan bp
    on bp.mabophan = nv.mabophan

-- câu 2: cho 
select madichvu, tendichvu, dongiadichvu
from dichvu dv
join loaidichvu ldv
    on dv.maloaidichvu = ldv.maloaidichvu

-- câu 3 so luong phong có trong ks
select tenloaiphong, count (lp.maloaiphong) as soluongphong
from phong p
join loaiphong lp
    on p.maloaiphong = lp.maloaiphong
group by tenloaiphong
    


-- câu 4 cho bi?t s? l??ng v?t tu c?a mõi phòng 
select  maphong, sum(soluongvattu) as slvattu
from ctvattu
group by maphong
order by maphong 

-- câu 5 
select makh, hokh, tenkh, gioitinh, diachi, dienthoai,
email, cmnd, tenloaikhachhang
from khachhang kh
join loaikhachhang lkh
    on kh.maloaikhachhang = lkh.maloaikhachhang
order by makh

-- câu 6 
select mahoadon, sotiendatcoc, ngaythuephong, ngaytraphong, 
sogiuong, giaphong, ngaylaphoadon
from hoadon hd
join ctphieuthuephong ctpt
    on hd.mactphieuthuephong = ctpt.mactphieuthuephong
join phieuthuephong ptp
    on ptp.maphieuthuephong = ctpt.maphieuthuephong
join phong p
    on p.maphong = ptp.maphong
join loaidichvu ldv
    on ldv.maloaidichvu = hd.maloaidichvu
where ngaylaphoadon between '01-FEB-16' and '13-FEB-16'


-- câu 7
select p.maphong, tenloaiphong, tenvattu, soluongvattu
from phong p
join ctvattu ctvt 
    on p.maphong = ctvt.maphong
join vattu vt
    on vt.mavattu = ctvt.mavattu
join loaiphong lp
    on lp.maloaiphong = p.maloaiphong
order by p.maphong

-- câu 8 tìm nhân viên sinh t? ngày A t?i ngày B
select manv, honv, tennv, dienthoai, ngaysinh
from nhanvien
where ngaysinh between '02-AUG-99' and '1-OCT-02'

-- câu 9 cho b?t khách hàng

select kh.makh, hokh, tenkh, ngaythuephong, ngaytraphong, sotiendatcoc
from khachhang kh
join phieuthuephong ptp
    on kh.makh = ptp.makh
join ctphieuthuephong ctpt
    on ctpt.maphieuthuephong = ptp.maphieuthuephong
order by sotiendatcoc

-- câu 10 cho bi?t phòng không v?t tu

select *
from phong
where maphong not in (select distinct maphong 
                        from ctvattu)
                        
-- câu 11 li?t kê danh sách nhân viên có ch? a trong tên nhân viên
select manv, honv, tennv, gioitinh, ngaysinh, diachi, dienthoai
from nhanvien
where tennv like '%a%'

-- cau 12 
select p.maphong, tenloaiphong, tentinhtrangphong,
sogiuong, giaphong *1.05 as GiaNew
from phong p
join loaiphong lp
    on p.maloaiphong = lp.maloaiphong    
join tinhtrangphong ttp
    on ttp.matinhtrangphong = p.matinhtrangphong

select * from phong

-- câu 13 cho bi?t tên nhân viên và chi?u dài t??ng ?ng c?a tên ??i v?i nh?ng tên co kí t? b?t ??u trong tên là ........ k?t qu? 

select  INITCAP(tennv), length (tennv) as "Chieu dai"
FROM nhanvien 
WHERE SUBSTR (tennv , 1,1 )  IN ( 'D' , 'A' , 'T' , 'M' ) 
ORDER BY tennv 

select * from nhanvien

-- câu 14 cho bi?t phòng có giá khác 1000000 và  2000000

select *
from phong
where giaphong not in ('1000000','2000000')


-- câu 15 cho phép nhân doanh thu c?a t?ng nhân viên
select NV.MANV, NV.HONV, NV.TENNV  ,  
sum( (ngaytraphong - ngaythuephong) * giaphong) as doanhthu
from NhanVien NV
join HOADON HD 
    ON NV.manv= hd.manv 
join ctphieuthuephong ctpt 
    on ctpt.mactphieuthuephong = hd.mactphieuthuephong
join phieuthuephong ptp 
    on ptp.maphieuthuephong = ctpt.maphieuthuephong
join phong 
    on phong.maphong = ptp.maphong
group by  NV.MANV, NV.HONV, NV.TENNV

select *
from nhanvien

-- câu 16 tính doanh thu nhân viên  cao nh?t 

select NV.MANV, NV.HONV, NV.TENNV  ,  sum( (ngaytraphong - ngaythuephong) * giaphong) as doanhthu
from NhanVien NV
join HOADON HD 
    ON NV.manv= hd.manv 
join ctphieuthuephong ctpt 
    on ctpt.mactphieuthuephong = hd.mactphieuthuephong
join phieuthuephong ptp 
    on ptp.maphieuthuephong = ctpt.maphieuthuephong
join phong 
    on phong.maphong = ptp.maphong
group by  NV.MANV, NV.HONV, NV.TENNV
having  sum ((ngaytraphong - ngaythuephong) * giaphong) = 
        (select  sum ( (ngaytraphong - ngaythuephong) * giaphong) 
         from NhanVien NV
         join HOADON HD 
            ON NV.manv= hd.manv 
         join ctphieuthuephong ctpt 
            on ctpt.mactphieuthuephong = hd.mactphieuthuephong
         join phieuthuephong ptp 
            on ptp.maphieuthuephong = ctpt.maphieuthuephong
         join phong 
            on phong.maphong = ptp.maphong
         group by  NV.MANV, NV.HONV, NV.TENNV 
         order by sum ( (ngaytraphong - ngaythuephong) * giaphong)desc 
         fetch first 1 rows only) ;

-- câu 17
-- T?o view cho phép xem thông tin khách hàng bao g?m: Mã khách hàng, H? tên, 
-- ??n giá, và phân lo?i khách hàng(Vãng lai, th??ng, ti?m n?ng) d?a trên ??n giá hóa ??n c?a m?i khách
SELECT kh.makh, hokh, tenkh,  sum( (ngaytraphong - ngaythuephong) * giaphong) AS GIA
,   case 
        when  sum((ngaytraphong - ngaythuephong) * giaphong) < 1000000 then 'Khach hang vang lai'
        when  sum((ngaytraphong - ngaythuephong) * giaphong) >= 1000000 
            and sum((ngaytraphong - ngaythuephong) * giaphong) <= 10000000  then 'Khach hang thuong'
        when  sum((ngaytraphong - ngaythuephong) * giaphong) > 10000000 then 'Khach hang VIP'
    end AS LOAIKH
FROM khachhang KH
join phieuthuephong ptp
    on kh.makh = ptp.makh 
join phong p
    on p.maphong = ptp.maphong
group by  kh.makh, hokh, tenkh;

-- câu 18 cho bi?t danh sách nhân viên có gi?i tính nam

select manv, honv, tennv, gioitinh, ngaysinh, diachi, dienthoai, email
from nhanvien
where Gioitinh like 'Nam'

-- câu 19 cho bi?t s? l??ng nhân viên nam và n? trong công ty

select distinct(select count (*) 
                from nhanvien 
                where gioitinh like 'Nam') as NAM 
        , (select count (*) 
            from nhanvien 
            where gioitinh like 'Nu') as Nu 
from Nhanvien

-- câu 20 cho bi?t nh?ng nhân viên làm cùng ch?c v?

select nv.manv, honv, tennv, gioitinh, ngaysinh, tenchucvu
from nhanvien nv
join chucvu cv
    on nv.machucvu =  cv.machucvu
order by cv.machucvu, tenchucvu

-- câu 21 cho bi?t mã s? ti?n l?n nh?t bé nh?t c?a t?ng lo?i phòng

select lp.maloaiphong, tenloaiphong, 
max (giaphong) as gialonnhat, min (giaphong) as giabenhat
from phong p
join loaiphong lp
    on p.maloaiphong = lp.maloaiphong
group by lp.maloaiphong, tenloaiphong


-- câu 22 cho bi?t s? l??ng nhân viên c?a t?ng b? ph?n

select bp.mabophan, tenbophan, count (manv)as SLNV
from nhanvien nv
join bophan bp
    on nv.mabophan = bp.mabophan
group by bp.mabophan, tenbophan

-- câu 23 li?t kê danh sách b? ph?n có ít h?n 3 nhân viên

select tenbophan, count (manv) as SLNV
from nhanvien nv
join bophan bp
    on nv.mabophan =  bp.mabophan
group by tenbophan
having count (manv) > '3'

-- câu 24 cho bi?t b? ph?n cso nhìu nhân viên nh?t, b? ph?n có nhân viên ít nh?t 

select tenbophan, count (manv) as SL
from nhanvien nv
join bophan bp
    on nv.mabophan =  bp.mabophan
group by tenbophan
having count (manv) >= all(select count (*)
                            from nhanvien
                            group by mabophan)
    or count (manv) <= all(select count (*)
                            from nhanvien
                            group by mabophan)
order by count (manv)

-- câu 25 li?t kê khách hàng có ti?n ??t c?c cao nh?t

select kh.makh, sum(sotiendatcoc) as tiendatcoc
from khachhang kh 
join phieuthuephong ptp
    on kh.makh = ptp.makh
join ctphieuthuephong ctpt
    on ctpt.maphieuthuephong = ptp.maphieuthuephong
group by kh.makh
having sum(sotiendatcoc) = (select  sum(sotiendatcoc)
                                from khachhang kh 
                                join phieuthuephong ptp
                                    on kh.makh = ptp.makh
                                join ctphieuthuephong ctpt
                                    on ctpt.maphieuthuephong = ptp.maphieuthuephong
                                group by kh.makh
                                order by sum(sotiendatcoc) desc
                                fetch first 1 rows only)

-- câu 26 li?t kê các nhân viên có cùng ch?c v? v?i nhân viên tr?n ??c

select nv.manv, honv, tennv, gioitinh, ngaysinh, tenchucvu
from nhanvien nv
join chucvu cv
    on nv.machucvu = cv.machucvu
where cv.machucvu = (select machucvu
                    from nhanvien
                    where honv like 'Tran'and tennv like 'Duc')

-- câu 27 t?ng giá phòng thêm 100000 n?u phòng d??i 4000000

select maphong, maloaiphong, sogiuong, giaphong + 100000 as giaphongmoi
from phong
where giaphong < '4000000'

-- câu 28 th?c hi?n câu truy v?n có k?t qu? sau 
select concat(concat(concat(concat(concat('maphong: ', maphong),
                        ' so giuong '),sogiuong),' gia phong '),giaphong) as KQ
from phong

-- câu 29 cho danh sách nh?ng khách hang vip

select makh, hokh, tenkh, gioitinh, diachi, dienthoai,email
from khachhang
where maloaikhachhang like 'LKH02'

-- câu 30 cho bi?t nh?ng v?t t? có trong khách s?n

select distinct vt.mavattu, tenvattu
from vattu vt
join ctvattu ctvt
    on vt.mavattu = ctvt.mavattu


-------------------------- user


----65.tao khong gian bang co kich thuoc 100m;
create tablespace oracle
datafile 'oracle.dbf' size 100m;

---66.Tao khong gian bang tam(temporary tablespace)
create temporary tablespace oracle
tempfile 'oracle.dbf' size 50m;

---67.Tao rollback segment
create rollback segment seg
tablespace oracle;

---68. Tao user ten la sinh vien
ALTER SESSION SET"_ORACLE_SCRIPT" = TRUE;
CREATE USER NHANVIEN1  IDENTIFIED BY 123456
PROFILE DEFAULT
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO NHANVIEN1  ;





-- c?p quy?n truy xu?t tài nguyên cho user v?a t?o

grant resource to NHANVIEN1   ;

-- 6.6	Caáp quyeàn cho phieân laøm vieäc (session) cho user v?a t?o.

grant create session to NHANVIEN1  ;

-- 6.7	Caáp quyeàn taïo baûng (table) cho user vöøa taïo.

grant create table to PHOGIAMDOC1
grant create view to PHOGIAMDOC1;
grant create procedure to PHOGIAMDOC1;

--6.8	Caáp quyeàn taïo khung nhìn (view) cho user vöøa taïo.




-- 6.9	Caáp quyeàn Select, Insert, Update, Delete treân baûng NhanVien cho user vöøa taïo.

grant insert, select, update, delete on NHANVIEN to GIAMDOC1;


grant select on NHANVIEN to NHANVIEN1 ;

-- thu h?i quy?n
revoke select on NHANVIEN from NHANVIEN1;

deny select on NHANVIEN from GIAMDOC1;


grant insert, select, update, delete on BOPHAN to nhanvien1;

--Xóa ng??i dùng
DROP USER NHANVIEN1;

GRANT select ANY TABLE TO nhanvien1;

REVOKE select ANY TABLE FROM NHANVIEN1;

SELECT * FROM user_sys_privs;

SELECT * FROM user_tab_privs_recd

create table tmp
(
    matmp number
)


GRANT SELECT ON NHANVIEN TO public;
GRANT SELECT,INSERT,UPDATE,DELETE ON NHANVIEN TO NHANVIEN1;


CREATE USER student IDENTIFIED BY 123456;

select * 
from chucvu


--- câu l?nh update delete 
-- xóa hóa ??n có mã hóa ??n là ...

INSERT INTO HOADON VALUES('HD0031tmp','GUI','NV0001','CTPTP001',TO_DATE('2023-08-13','yyyy/mm/dd'));
select * 
from hoadon
 
delete hoadon
where mahoadon = 'HD0031tmp'

select * from khachhang


update khachhang
set tenkh = 'Kiett'
where makh = 'KH002'

rollback

select * from nhanvien


select * from phong


delete dichvu
where maloaidichvu in (select maloaidichvu
                        from loaidichvu 
                        where dongiadichvu = '500000')

update dichvu
set tendichvu = 'Thuê Xe ??a ?ón'
where maloaidichvu in (select maloaidichvu
                        from loaidichvu 
                        where dongiadichvu = '500000')

select * from dichvu


select * from loaidichvu


INSERT INTO DICHVU VALUES ('DV003','DUA','Thue Xe Dua Don');



--------- 
-- c?p nh?t s? giá phòng t?ng thêm 500000 v?i nh?ng phòng m?i ch?a có v?t t?

update phong
set giaphong = 8000000
where maphong in (select *
                from phong
                where maphong not in (select distinct maphong
                                    from ctvattu ))


update phong
set giaphong = giaphong + 500000
where maphong in (select *
                    from phong
                    where giaphong  <= '5000000')

select * 
from phong
where giaphong  <= '4000000'



-----

INSERT INTO LOAIDICHVU VALUES('tmp',1100000,TO_DATE('2019/03/09','yyyy/mm/dd'));--Thue quay bar

select *
from LOAIDICHVU


update loaidichvu 
set dongiadichvu = '1'
where maloaidichvu = 'tmp'

delete loaidichvu
where maloaidichvu = 'tmp'

select * from chucvu

--NV0020 12
select * from nhanvien 
where manv = 'NV0012'

update nhanvien
set machucvu = 'CV03'
where manv in ( select NV.MANV
                from NhanVien NV
                join HOADON HD 
                    ON NV.manv= hd.manv 
                join ctphieuthuephong ctpt 
                    on ctpt.mactphieuthuephong = hd.mactphieuthuephong
                join phieuthuephong ptp 
                    on ptp.maphieuthuephong = ctpt.maphieuthuephong
                join phong 
                    on phong.maphong = ptp.maphong
                group by  NV.MANV
                having  sum ((ngaytraphong - ngaythuephong) * giaphong) = 
                    ( select  sum ( (ngaytraphong - ngaythuephong) * giaphong) 
                    from NhanVien NV
                    join HOADON HD 
                       ON NV.manv= hd.manv 
                    join ctphieuthuephong ctpt 
                       on ctpt.mactphieuthuephong = hd.mactphieuthuephong
                    join phieuthuephong ptp 
                       on ptp.maphieuthuephong = ctpt.maphieuthuephong
                    join phong 
                       on phong.maphong = ptp.maphong
                    group by  NV.MANV
                    order by sum ( (ngaytraphong - ngaythuephong) * giaphong)  desc
                    fetch first 1 rows only) )
--09-DEC-22
select * from hoadon

update hoadon
set ngaylaphoadon = '09-DEC-22'
where mahoadon = 'HD0031'

delete dichvu 
where madichvu = 'DV003x'
-- Transaction
begin tran;

INSERT INTO DICHVU VALUES ('DVtmpcommit','DUA','Thue Xe Dua Don');

select * 
from dichvu

COMMIT

ROLLBACK

SET TRANSACTION  NAME 'TMP1';

SET TRANSACTION  READ WRITE  ;



--- window function
SELECT maphong, sogiuong, giaphong, donvitinh,
RANK() OVER (PARTITION BY maphong ORDER BY sogiuong desc) as thutu
FROM PHONG;


select maphong, sogiuong, giaphong, donvitinh,
RANK() OVER (ORDER BY GIAPHONG DESC) AS THUTU
FROM PHONG


select kh.makh, ngaythuephong, ngaytraphong
RANK() OVER (PARTITION BY kh.makh ORDER BY ngaysinh desc) as thutu
from khachhang kh
join phieuthuephong ptp 
    on kh.makh = ptp.makh
    
SELECT maphong, sogiuong, giaphong, donvitinh,
RANK() OVER (PARTITION BY sogiuong ORDER BY giaphong DESC) as thutu
FROM PHONG;


--------------------------------------- rang buoc mien gia tri

alter table nhanvien 
add constraint chk_nv_gioitinh check (gioitinh in ('Nam','Nu','Khac'))



alter table khachhang 
add constraint chk_kh_gioitinh check (gioitinh in ('Nam','Nu','Khac'))


alter table ctphieuthuephong
add constraint chk_ctptp_tiendatcoc check (sotiendatcoc > 0)


alter table tinhtrangphong
add constraint chk_ttphong_tentinhtrang 
    check (tentinhtrangphong in ('Phong trong','Phong da co nguoi dat','Phong da co nguoi o'))

select * 
from tinhtrangphong

select *
from loaikhachhang

alter table loaikhachhang
add constraint chk_loaikh_tenlkh 
    check (tenloaikhachhang in ('Khach hang moi','Khach hang VIP'))

select *
from PHONG

alter table phong
add constraint  chk_phong_giaphong check (giaphong > 0)

alter table loaidichvu
add constraint chk_loaidv_dgdichvu check (dongiadichvu >= 0)

alter table chucvu
add constraint U_chucvu_tencv unique (TenChucVu)

select * 
from loaikhachhang

alter table loaikhachhang
add constraint U_loaikh_tenloaikh unique (Tenloaikhachhang)

select *
from tinhtrangphong

alter table tinhtrangphong
add constraint U_ttphong_tenttphong unique (Tentinhtrangphong)


select *
from dichvu

alter table dichvu
add constraint U_dichvu_tendv unique (TenDichVu)

alter table bophan
add constraint U_bophan_tenbp unique (tenbophan)

alter table tinhtrangphong
MODIFY tentinhtrangphong varchar2(100) default  'Phong trong'  

select *
from tinhtrangphong


alter table hoadon
MODIFY ngaylaphoadon date default sysdate






